parameters:
    apache.type.modules:
        rewrite: rewrite 
        actions: actions
        asis: asis
        auth_digest: auth_digest
        authn_alias: authn_alias
        authn_anon: authn_anon
        authn_dbd: authn_dbd
        authn_dbm: authn_dbm
        authn_default: authn_default
        authnz_ldap: authnz_ldap
        authz_dbm: authz_dbm
        authz_owner: authz_owner
        cache: cache
        cern_meta: cern_meta
        cgid: cgid
        charset_lite: charset_lite
        dav_fs: dav_fs
        dav: dav
        dav_lock: dav_lock
        dbd: dbd
        disk_cache: disk_cache
        dump_io: dump_io
        expires: expires
        ext_filter: ext_filter
        file_cache: file_cache
        filter: filter
        headers: headers
        ident: ident
        imagemap: imagemap
        include: include
        info: info
        ldap: ldap
        log_forensic: log_forensic
        mem_cache: mem_cache
        mime_magic: mime_magic
        proxy_ajp: proxy_ajp
        proxy_balancer: proxy_balancer
        proxy_connect: proxy_connect
        proxy_ftp: proxy_ftp
        proxy_http: proxy_http
        proxy: proxy
        proxy_scgi: proxy_scgi
        speling: speling
        ssl: ssl
        substitute: substitute
        suexec: suexec
        unique_id: unique_id
        userdir: userdir
        usertrack: usertrack
        version: version
        vhost_alias: vhost_alias